export const scriptSegundaVia = {
    // SEGUNDA VIA DA FATURA
    // PROTOCOLO
    'gerou o protocolo': 'Ta bom',
    'criou o protocolo': 'Ok',
    'gerado protocolo': 'Ta bom',
    'gostaria de saber': 'Sim',
    'protocolo': 'Ok',
    
    // Após envio
    'enviei': 'Sim, já chegou no meu e-mail.',
    'encaminhei': 'Sim, já chegou no meu e-mail.',
    'enviado': 'Sim, já chegou no meu e-mail.',
    'enviada': 'Sim, já chegou no meu e-mail.',
    'encaminhado': 'Sim, já chegou no meu e-mail.',
    'encaminhada': 'Sim, já chegou no meu e-mail.',
    'verifica se chegou': 'Sim, já chegou no meu e-mail.',
    'verifique se chegou': 'Sim, já chegou no meu e-mail.',
    'verifique se consta': 'Sim, já chegou no meu e-mail.',
    
    // OI E OLÁ
    'oi': 'Olá',
    'ola': 'Oi',
    'olá': 'Oi',
    
    // DIA
    'bom dia': 'Bom dia',
    'boa tarde': 'Boa tarde',
    'boa noite': 'Boa noite',
    
    // Finalização
    'ajudar em algo mais': 'Não, tudo certo obrigado',
    'te ajudar em algo mais': 'Não, tudo certo obrigado',
    'ajudo em algo mais': 'Não, tudo certo obrigado',
    'ajudando em algo mais': 'Não, tudo certo obrigado',
    'ajuda-lo em algo mais': 'Não, tudo certo obrigado',
    'ajudá-lo em algo mais': 'Não, tudo certo obrigado',
    'agradece seu': 'Obrigado',
    'agradece o': 'Obrigado',
    'avalie': 'O atendimento foi bom',
    'avalia': 'O atendimento foi bom',
    'avaliaçao': 'O atendimento foi bom',
    'avaliação': 'O atendimento foi bom',
    'em nome da': 'Obrigado',

    //TUDO BEM
    'tudo bem': 'Estou bem', 
    'como vai': 'Oi, estou bem e você?',
    'como voce esta': 'Estou bem e você?',
    'como você está': 'Estou bem e você?',
    'como esta': 'Estou bem e você?',
    'como está': 'Estou bem e você?',
    'que bom': 'Poderia me ajudar',
    
    // ESTOU BEM
    'estou bem': 'Que bom',
    'to bem': 'Que bom',
    'tô bem': 'Que bom',
    'estou otimo': 'Que bom',
    'to otimo': 'Que bom',
    'tô otimo': 'Que bom',
    'estou otima': 'Que bom',
    'to otima': 'Que bom',
    'tô otima': 'Que bom',
    'estou ótimo': 'Que bom',
    'to ótimo': 'Que bom',
    'tô ótimo': 'Que bom',
    'estou ótima': 'Que bom',
    'to ótima': 'Que bom',
    'tô ótima': 'Que bom',
    'tudo, e voce': 'Estou bem também',
    'tudo e voce': 'Estou bem também',
    'tudo, e você': 'Estou bem também',
    'tudo e você': 'Estou bem também',
    'tudo otimo e com voce': 'Estou bem também',
    'tudo ótimo e com você': 'Estou bem também',
    'tudo otimo e com você': 'Estou bem também',
    'tudo ótimo e com voce': 'Estou bem também',
    'tudo otimo, e com voce': 'Estou bem também',
    'tudo ótimo, e com você': 'Estou bem também',
    'tudo otimo, e com você': 'Estou bem também',
    'tudo ótimo, e com voce': 'Estou bem também',
    'tudo e com voce': 'Estou bem também',
    'tudo e com você': 'Estou bem também',
    
    // AJUDA
    'posso ajudar': 'Quero a segunda via da fatura por email',
    'posso te ajudar': 'Quero a segunda via da fatura por email',
    'posso ajuda-lo': 'Quero a segunda via da fatura por email',
    'posso te ajuda-lo': 'Quero a segunda via da fatura por email',
    'posso ajudá-lo': 'Quero a segunda via da fatura por email',
    'posso te ajudá-lo': 'Quero a segunda via da fatura por email',
    'é o problema': 'Quero a segunda via da fatura por email',
    'seria o problema': 'Quero a segunda via da fatura por email',
    'motivo do contato': 'Quero a segunda via da fatura por email',
    'motivo do atendimento': 'Quero a segunda via da fatura por email',
    'bom dia posso ajudar': 'Bom dia quero a segunda via da fatura por email',
    'boa tarde posso ajudar': 'Boa tarde quero a segunda via da fatura por email',
    
    //CONFIRMAÇÃO DE DADOS
    'cpf e nome completo do titular': 'Teste CPF 999.999.999-99',
    'cpf e nome do titular': 'Teste CPF 999.999.999-99',
    'cpf e o nome completo do titular': 'Teste CPF 999.999.999-99',
    'cpf e o nome do titular': 'Teste CPF 999.999.999-99',
    'cpf': '999.999.999-99',
    'nome do titular': 'Teste',
    'nome completo do titular': 'Teste',

    // AGRADECE
    'obrigado': 'De nada',
    'obrigada': 'De nada',
    'obrigado pela confirmaçao de dados': 'De nada',
    'obrigado pela confirmação de dados': 'De nada',
    'obrigada pela confirmaçao de dados': 'De nada',
    'obrigada pela confirmação de dados': 'De nada',

    // LOCALIZANDO CONTRATO
    'localizar o cadastro':'Ta bom',
    'localizando o cadastro':'Ok',
    'localizar seu cadastro':'Ta ok',
    'localizando seu cadastro':'Ta bom',
    'localizar o seu cadastro':'Ok',
    'localizando o seu cadastro':'Ta ok',
    'localizar o contrato':'Ta bom',
    'localizando o contrato':'Ok',
    'localizar o seu contrato':'Ta ok',
    'localizando o seu contrato':'Ta bom',
    'localizar seu contrato':'Ok',
    'localizando seu contrato':'Ta ok',
    'identificar o cadastro':'Ta bom',
    'identificar o seu cadastro':'Ok',
    'identificar seu cadastro':'Ta ok',
    'identificando seu cadastro':'Ta bom',
    'identificando o cadastro':'Ok',
    'identificando o seu cadastro':'Ta ok',
    'identificar seu contrato':'Ta bom',
    'identificando seu contrato':'Ok',
    'identificar o seu contrato':'Ta ok',
    'identificando o seu contrato':'Ta bom',
    'identificar o contrato':'Ok',
    'identificando o contrato':'Ta ok',
    'procurando o cadastro': 'Ta bom',
    'procurando o seu cadastro': 'Ok',
    'procurando seu cadastro': 'Ta ok',
    'procurando o contrato': 'Ta bom',
    'procurando o seu contrato': 'Ok',
    'procurando seu contrato': 'Ta ok',

    // UM MOMENTO
    'momento': 'Certo',
    'instante': 'Ta',
    'instantes': 'Beleza',
    'minutos': 'Ok',

    // CONFIRMAÇÃO DE EMAIL
    'incorreto': 'Mas este é meu email',
    'email': 'naotem12321312@email.com',
    'e-mail': 'naotem12321312@email.com',

    // QUAL FATURA
    'mês': 'Quero a desse mês',
    'mes': 'Quero a desse mês',
    'qual fatura': 'Quero a desse mês',

    // APP
    'app': 'Ok',
    'play store': 'Ok',
    'playstore': 'Ok',
    'app store': 'Ok',
    'appstore': 'Ok',
    'aplicativo': 'Ok',
}

export const scriptSemSinal = {
    // SEM SINAL
    // PROTOCOLO
    'gerou o protocolo': 'Ta bom',
    'criou o protocolo': 'Ok',
    'gerado protocolo': 'Ta bom',
    'gostaria de saber': 'Sim',
    'protocolo': 'Ok',
    
    // OI E OLÁ
    'oi': 'Olá',
    'ola': 'Oi',
    'olá': 'Oi',
    
    // DIA
    'bom dia': 'Bom dia',
    'boa tarde': 'Boa tarde',
    'boa noite': 'Boa noite',
    
    // Finalização
    'ajudar em algo mais': 'Não, tudo certo obrigado',
    'te ajudar em algo mais': 'Não, tudo certo obrigado',
    'ajudo em algo mais': 'Não, tudo certo obrigado',
    'ajudando em algo mais': 'Não, tudo certo obrigado',
    'ajuda-lo em algo mais': 'Não, tudo certo obrigado',
    'ajudá-lo em algo mais': 'Não, tudo certo obrigado',
    'agradece seu': 'Obrigado',
    'agradece o': 'Obrigado',
    'avalie': 'O atendimento foi bom',
    'avalia': 'O atendimento foi bom',
    'avaliaçao': 'O atendimento foi bom',
    'avaliação': 'O atendimento foi bom',
    'em nome da': 'Obrigado',

    //TUDO BEM
    'tudo bem': 'Estou bem', 
    'como vai': 'Oi, estou bem e você?',
    'como voce esta': 'Estou bem e você?',
    'como você está': 'Estou bem e você?',
    'como esta': 'Estou bem e você?',
    'como está': 'Estou bem e você?',
    'que bom': 'Poderia me ajudar',
    
    // ESTOU BEM
    'estou bem': 'Que bom',
    'to bem': 'Que bom',
    'tô bem': 'Que bom',
    'estou otimo': 'Que bom',
    'to otimo': 'Que bom',
    'tô otimo': 'Que bom',
    'estou otima': 'Que bom',
    'to otima': 'Que bom',
    'tô otima': 'Que bom',
    'estou ótimo': 'Que bom',
    'to ótimo': 'Que bom',
    'tô ótimo': 'Que bom',
    'estou ótima': 'Que bom',
    'to ótima': 'Que bom',
    'tô ótima': 'Que bom',
    'tudo, e voce': 'Estou bem também',
    'tudo e voce': 'Estou bem também',
    'tudo, e você': 'Estou bem também',
    'tudo e você': 'Estou bem também',
    'tudo otimo e com voce': 'Estou bem também',
    'tudo ótimo e com você': 'Estou bem também',
    'tudo otimo e com você': 'Estou bem também',
    'tudo ótimo e com voce': 'Estou bem também',
    'tudo otimo, e com voce': 'Estou bem também',
    'tudo ótimo, e com você': 'Estou bem também',
    'tudo otimo, e com você': 'Estou bem também',
    'tudo ótimo, e com voce': 'Estou bem também',
    'tudo e com voce': 'Estou bem também',
    'tudo e com você': 'Estou bem também',
    
    // AJUDA
    'posso ajudar': 'Estou sem sinal de internet',
    'posso te ajudar': 'Estou sem sinal de internet',
    'posso ajuda-lo': 'Estou sem sinal de internet',
    'posso te ajuda-lo': 'Estou sem sinal de internet',
    'posso ajudá-lo': 'Estou sem sinal de internet',
    'posso te ajudá-lo': 'Estou sem sinal de internet',
    'é o problema': 'Estou sem sinal de internet',
    'seria o problema': 'Estou sem sinal de internet',
    'motivo do contato': 'Estou sem sinal de internet',
    'motivo do atendimento': 'Estou sem sinal de internet',
    'bom dia posso ajudar': 'Bom dia estou sem sinal de internet',
    'boa tarde posso ajudar': 'Boa tarde estou sem sinal de internet',
    
    //CONFIRMAÇÃO DE DADOS
    'cpf e nome completo do titular': 'Teste CPF 999.999.999-99',
    'cpf e nome do titular': 'Teste CPF 999.999.999-99',
    'cpf e o nome completo do titular': 'Teste CPF 999.999.999-99',
    'cpf e o nome do titular': 'Teste CPF 999.999.999-99',
    'cpf': '999.999.999-99',
    'nome do titular': 'Teste',
    'nome completo do titular': 'Teste',

    // AGRADECE
    'obrigado': 'De nada',
    'obrigada': 'De nada',
    'obrigado pela confirmaçao de dados': 'De nada',
    'obrigado pela confirmação de dados': 'De nada',
    'obrigada pela confirmaçao de dados': 'De nada',
    'obrigada pela confirmação de dados': 'De nada',

    // LOCALIZANDO CONTRATO
    'localizar o cadastro':'Ta bom',
    'localizando o cadastro':'Ok',
    'localizar seu cadastro':'Ta ok',
    'localizando seu cadastro':'Ta bom',
    'localizar o seu cadastro':'Ok',
    'localizando o seu cadastro':'Ta ok',
    'localizar o contrato':'Ta bom',
    'localizando o contrato':'Ok',
    'localizar o seu contrato':'Ta ok',
    'localizando o seu contrato':'Ta bom',
    'localizar seu contrato':'Ok',
    'localizando seu contrato':'Ta ok',
    'identificar o cadastro':'Ta bom',
    'identificar o seu cadastro':'Ok',
    'identificar seu cadastro':'Ta ok',
    'identificando seu cadastro':'Ta bom',
    'identificando o cadastro':'Ok',
    'identificando o seu cadastro':'Ta ok',
    'identificar seu contrato':'Ta bom',
    'identificando seu contrato':'Ok',
    'identificar o seu contrato':'Ta ok',
    'identificando o seu contrato':'Ta bom',
    'identificar o contrato':'Ok',
    'identificando o contrato':'Ta ok',
    'procurando o cadastro': 'Ta bom',
    'procurando o seu cadastro': 'Ok',
    'procurando seu cadastro': 'Ta ok',
    'procurando o contrato': 'Ta bom',
    'procurando o seu contrato': 'Ok',
    'procurando seu contrato': 'Ta ok',

    // UM MOMENTO
    'momento': 'Certo',
    'instante': 'Ta',
    'instantes': 'Beleza',
    'minutos': 'Ok',

    // APP
    'app': 'Ok',
    'play store': 'Ok',
    'playstore': 'Ok',
    'app store': 'Ok',
    'appstore': 'Ok',
    'aplicativo': 'Ok',

    // VERIFICANDO
    'vou verificar': 'Ta',
    'estou verificando': 'Ta bom',
    'vou analisar': 'Ok',
    'estou analisando': 'Ta',
    'vou acompanhar': 'Ok',
    'estou acompanhando': 'Ta bom',

    // PROBLEMA MASSIVO
    'massivo na sua região': 'E vai ser descontado da fatura depois esse tempo sem internet?',
    'massivo em sua região': 'E vai ser descontado da fatura depois esse tempo sem internet?',
    'massivo na sua estrutura': 'E vai ser descontado da fatura depois esse tempo sem internet?',
    'massivo em sua estrutura': 'E vai ser descontado da fatura depois esse tempo sem internet?',
    'massivo no poste': 'E vai ser descontado da fatura depois esse tempo sem internet?',
    'massivo na caixa do poste': 'E vai ser descontado da fatura depois esse tempo sem internet?',

    // DESCONTO
    'solicitar o desconto': 'Ok',

    // LEDS DO EQUIPAMENTO
    'luz acesa no equipamento': 'Sim tem uma luz vermelha',
    'luz acesa no nosso equipamento': 'Sim tem uma luz vermelha',
    'luz acesa no seu equipamento': 'Sim tem uma luz vermelha',
    'luz acesa em nosso equipamento': 'Sim tem uma luz vermelha',
    'luz acesa em seu equipamento': 'Sim tem uma luz vermelha',
    'luz acesa no aparelho': 'Sim tem uma luz vermelha',
    'luz acesa no seu aparelho': 'Sim tem uma luz vermelha',
    'luz acesa no nosso aparelho': 'Sim tem uma luz vermelha',
    'luz acesa em nosso aparelho': 'Sim tem uma luz vermelha',
    'luz acesa em seu aparelho': 'Sim tem uma luz vermelha',
    'led aceso': 'Sim tem uma luz vermelha',

    //REINICIAR O EQUIPAMENTO
    'desliga o equipamento': 'Desliguei',
    'desligue o equipamento': 'Desliguei',
    'desliga os equipamentos': 'Desliguei',
    'desligue os equipamentos': 'Desliguei',
    'desligue-o': 'Desliguei',
    'desligue-os': 'Desliguei',
    'desligue ele': 'Desliguei',
    'desliga ele': 'Desliguei',
    'desliga no botao': 'Desliguei',
    'desliga no botão': 'Desliguei',
    'desligue no botao': 'Desliguei',
    'desligue no botão': 'Desliguei',
    'desligue-o no botao': 'Desliguei',
    'desligue-o no botão': 'Desliguei',
    'desligue-os no botao': 'Desliguei',
    'desligue-os no botão': 'Desliguei',
    'desliga no botão': 'Desliguei',
    'desliga pelo botao': 'Desliguei',
    'desligue pelo botao': 'Desliguei',
    'desligue pelo botão': 'Desliguei',
    'desligue-o pelo botão': 'Desliguei',
    'desligue-o pelo botao': 'Desliguei',
    'desliga pelo botão': 'Desliguei',
    'desliga através do botão': 'Desliguei',
    'desliga atraves do botao': 'Desliguei',
    'pode ligar': 'Liguei',
    'pode ligá-los': 'Liguei',
    'pode liga-los': 'Liguei',
    'ligou': 'Liguei',

    //AGENDAR VISITA
    'agendar uma visita': 'Preciso o mais rápido possível, não posso ficar sem internet',
    'agendar a visita': 'Preciso o mais rápido possível, não posso ficar sem internet',
    'agendando uma visita': 'Preciso o mais rápido possível, não posso ficar sem internet',
    'agendando a visita': 'Preciso o mais rápido possível, não posso ficar sem internet',
    'agendamento para': 'Não tem como ser hoje?',
    'agendamento em': 'Não tem como ser hoje?',
    'agendamento mais próximo': 'Não tem como ser hoje?',
    'agendamento mais proximo': 'Não tem como ser hoje?',
    'horário mais próximo': 'Não tem como ser hoje?',
    'horario mais proximo': 'Não tem como ser hoje?',
    'período mais próximo': 'Não tem como ser hoje?',
    'periodo mais proximo': 'Não tem como ser hoje?',
    'horário': 'Ok',
    'horario': 'Ok',
    'esta agendado': 'Tabom',
    'está agendado': 'Tabom',
    'agendei': 'Certo',
    'agendado': 'Ta bom',

    // CONFIRMANDO ENDEREÇO E TELEFONE
    'endereço e numero para contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço e numero de contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço e número para contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço e número de contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço e um numero para contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço e um numero de contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço e um número para contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço e um número de contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'numero para contato e endereço': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'numero de contato e endereço': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'número para contato e endereço': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'número de contato e endereço': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'um numero para contato e endereço': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'um numero de contato e endereço': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'um número para contato e endereço': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'um número de contato e endereço': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço completo e numero para contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço completo e numero de contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço completo e número para contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço completo e número de contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço completo e um numero para contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço completo e um numero de contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço completo e um número para contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço completo e um número de contato': 'Rua testador do teste número 10 bairro teste cidade testelândia (99) 99999-9999',
    'endereço completo': 'Rua testador do teste número 10 bairro teste cidade testelândia',
    'numero para contato': '(99) 99999-9999',
    'numero de contato': '(99) 99999-9999',
    'número para contato': '(99) 99999-9999',
    'número de contato': '(99) 99999-9999',
    'cep': '11.111-111',

    // CONFIRMANDO SE VOLTOU O SINAL
    'voltou o sinal': 'Ainda está sem sinal',
    'retornou o sinal': 'Ainda está sem sinal',
    'voltou a conexão': 'Ainda está sem internet',
    'retornou a conexão': 'Ainda está sem internet',
    'normalizou o acesso': 'Não voltou',
}

export const aguardandoCalmo = [
    'Estou aguardando o atendimento.', 'Oi', '?', 'Cade meu atendimento', 'Estou no aguardo',
    'Olá', 'Ola', 'Olá?', 'Alguém?',
    'Quando vão me atender ?', 'KD o atendimento', 'Alguem',
]

export const aguardandoIrritado = [
    'Se demora assim imagina quando eu precisar de atendimento urgente', 
    'Estou tentando contato com vcs e ninguem me responde', '????', 'Nunca sou atendido', '??',
    'Eai meu cadê vcs', 'Atendimento demorado', 'vai me atender ou vai me transferir ?',
    'Essa empresa so enrola', 'To perdendo meu tempo pra isso', 'essa esperar vai levar o dia todo ???', 'pede um momento para o cliente e nunca mais volta',
    'Na hora de contratar vocês são todos atenciosos', 'Vão me transferir de novo?',
]

export const respostaDesconhecida = [
    'nao entendi', 'Não entendi', '?', 'Não estou te entendendo', 'Que isso', '??', 'nao estou compreendendo',
    'Como assim', 'Hã', 'O que quer dizer',
]
